name: rikako
options:
  deploymentTarget:
    iOS: 14.0
  postGenCommand: bundle exec pod install

packages:
  R.swift.Library:
    url: https://github.com/mac-cain13/R.swift.Library
    from: 5.4.0
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI.git
    from: 2.0.2
schemes:
  rikako-local:
    build:
      targets:
        rikako-local: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - name: RikakoTests
          parallelizable: true
          randomExecutionOrder: true
  fp-production:
    build:
      targets:
        fp-production: all
    run:
      config: Debug
  chemist-production:
    build:
      targets:
        chemist-production: all
    run:
      config: Debug

targets:
  rikako-local:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: rikako
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.rikako.local
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: rikako/Info.plist
        MARKETING_VERSION: 3.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: icon-local
        SWIFT_OPTIMIZATION_LEVEL: -Onone
      configs:
        Debug:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
        Release:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
    dependencies:
      - package: R.swift.Library
        product: Rswift
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/rikako/Generated/R.generated.swift
  fp-production:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: rikako
    dependencies:
      - package: R.swift.Library
        product: Rswift
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/rikako/Generated/R.generated.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.fp
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: rikako/Info.plist
        MARKETING_VERSION: 3.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: icon-fp-production
        SWIFT_OPTIMIZATION_LEVEL: -Onone
      configs:
        Debug:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
        Release:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
    dependencies:
      - package: R.swift.Library
        product: Rswift
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
  chemist-production:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: rikako
    dependencies:
      - package: R.swift.Library
        product: Rswift
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/rikako/Generated/R.generated.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.conol.chemist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: rikako/Info.plist
        MARKETING_VERSION: 3.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: icon-chemist-production
        SWIFT_OPTIMIZATION_LEVEL: -Onone
      configs:
        Debug:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
        Release:
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
    dependencies:
      - package: R.swift.Library
        product: Rswift
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
  RikakoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - rikakoTests
    settings:
      base:
        INFOPLIST_FILE: rikakoTests/Info.plist
    dependencies:
      - target: rikako-local
  RikakoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - rikakoUITests
    settings:
      base:
        INFOPLIST_FILE: rikakoUITests/Info.plist
    dependencies:
      - target: rikako-local
